{{- if .Values.proxy.chp.pdb.enabled -}}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
{{- /* k8s 1.21+ required */ -}}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "jupyterhub.proxy.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  {{- if not (typeIs "<nil>" .Values.proxy.chp.pdb.maxUnavailable) }}
  maxUnavailable: {{ .Values.proxy.chp.pdb.maxUnavailable }}
  {{- end }}
  {{- if not (typeIs "<nil>" .Values.proxy.chp.pdb.minAvailable) }}
  minAvailable: {{ .Values.proxy.chp.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
{{- end }}
