---
# tasks file for nginx
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "{{ helm_chart_url }}"

- name: Add carrier directory
  command: "mkdir {{ ansible_env.HOME }}/carrier"

- name: add templ
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/carrier/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: "value.yaml.j2", dest: "nginx-values.yaml" }

# - name: Install Nginx Chart
#   kubernetes.core.helm:
#     name: nginx-server
#     namespace: testing2
#     chart_ref: bitnami/nginx
#     values_files:
#       - /home/centos/carrier/nginx-values.yaml

# - name: Gather information about nginx-server
#   kubernetes.core.helm_info:
#     name: nginx-server
#     release_namespace: testing2