---
# tasks file for tmp
# - name: Add helm repo
#   kubernetes.core.helm_repository:
#     name: bitnami
#     repo_url: "{{ helm_chart_url }}"

- name: helm update
  kubernetes.core.helm-repository:

- name: Nexus Template add in Master[0]
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/carrier/{{ item.dest }}"
    mode: 0644
  with_items:
    #- { src: "value.yaml.j2", dest: "nexus-values.yaml" }
    - { src: "value-upgrade.yaml.j2", dest: "nexus-values.yaml" }

- name: Install Nexus
  kubernetes.core.helm:
    name: nexus
    kubeconfig: "{{ kubeconfig }}"
    atomic: true    # 설치 실패시 삭제 처리
    chart_ref: "{{ helm_repository_name }}/nexus-repository-manager"
    #chart_version: "29.0.2"
    chart_version: "36.0.0"
    release_namespace: "addon"
    create_namespace: true
    values_files:
      - "{{ helm_value_dir }}/nexus-values.yaml"