---
- hosts: masters[0]
  remote_user: "{{ remote_user }}"
  vars:
    removed:  
      koreboard: false
      kong: false
      gitlab: false
      argocd: false
      nexus: false
      jaeger: false
      grafana: false
      kiali: false
      istio: false
      prometheus: false
      kubesphere: false
      consul: true

    chart_version:
      kiali-operator: "1.30.0"
      consul: "0.37.0"

  tasks:

  - name: consul helm remove in cluster
    when: "{{ removed.consul }}"
    kubernetes.core.helm:
      name: "{{ consul }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ consul }}"
      state: absent
      wait: true

  - name: consul get pvc list
    when: "{{ removed.consul }}"
    kubernetes.core.k8s_info:
      kubeconfig: "{{ kubeconfig }}"
      namespace: "{{ consul }}"
      kind: PersistentVolumeClaim
      api_version: v1
    register: pvc_list
  
  # - debug:
  #     msg: "{{ item }}"
  #   with_items: "{{ pvc_list['resources']|map(attribute='metadata.name')|list }}"

  - name: consul pvc remove in cluster
    when: "{{ removed.consul }}"
    kubernetes.core.k8s:
      name: "{{ item }}"
      kubeconfig: "{{ kubeconfig }}"
      namespace: "{{ consul }}"
      kind: PersistentVolumeClaim
      api_version: v1
      state: absent
      wait: true
    with_items: "{{ pvc_list['resources']|map(attribute='metadata.name')|list }}"

  # - name: grafana helm remove in cluster
  #   when: "{{ removed.grafana }}"
  #   kubernetes.core.helm:
  #     name: "{{ grafana }}"
  #     kubeconfig: "{{ kubeconfig }}"
  #     release_namespace: "{{ monitoring_namespace }}"
  #     state: absent
  #     wait: true

  # - name: kubesphere k8s remove in cluster
  #   when: "{{ removed.kubesphere }}"
  #   kubernetes.core.k8s:
  #     name: "{{ kubesphere }}"
  #     kubeconfig: "{{ kubeconfig }}"
  #     namespace: "{{ kubesphere_namespace }}"
  #     kind: kubesphere
  #     api_version: kubesphere.io/v1alpha1
  #     state: absent
  #     wait: true

  # - name: kubesphere helm remove in cluster
  #   when: "{{ removed.kubesphere }}"
  #   shell:
  #     "{{ ansible_env.HOME }}/carrier/kubesphere-delete.sh"

  # - name: istio k8s remove in cluster
  #   when: "{{ removed.istio }}"
  #   command: >-
  #     istioctl x uninstall 
  #     --kubeconfig='{{kubeconfig}}' 
  #     -f {{ ansible_env.HOME }}/carrier/{{ istio }}.yaml 
  #     --purge 
  #     --skip-confirmation