apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ template "namespace" . }}
spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.ports.http }}
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: {{ .Values.ports.https }}
      name: https
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: {{ .Values.ports.ssh }}
      name: ssh
  type: NodePort