{{- $fullName := include "pyspark.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName | quote }}
  labels:
    {{- include "pyspark.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pyspark.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ $fullName | quote }}
  apiGroup: rbac.authorization.k8s.io
