installed:
  koreboard: false
  kong: false
  gitlab: false
  argocd: false
  nexus: false
  jaeger: false
  grafana: false
  kiali: false
  istio: false
  prometheus: false

chart_version:
  zabbix: "0.3.2"
  koreboard: "0.4.0"
  nexus: "29.0.2"
  prometheus: "14.1.1"
  kiali-operator: "1.30.0"
  jaeger-operator: "2.21.30"
  grafana: "6.11.0"