installed:
  koreboard: true
  kong: true
  gitlab: true
  argocd: true
  nexus: false
  jaeger: true
  grafana: true
  kiali: true
  istio: true
  prometheous: true

removed:
  koreboard: true
  kong: true
  gitlab: true
  argocd: true
  nexus: false
  jaeger: true
  grafana: true
  kiali: true
  istio: true
  prometheous: true

chart_version:
  zabbix: "0.3.2"
  koreboard: "0.4.0"
  nexus: "29.0.2"
  kong: "2.1.0"
  konga: "1.0.0"
  argocd: "3.26.8"