apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: spark-operator
  namespace: argocd
spec:
  arguments: {}
  entrypoint: sparkapp-operator
  templates:
  - name: sparkapp-operator
    resource:
      action: create
      manifest: |
        apiVersion: "sparkoperator.k8s.io/v1beta2"
        kind: SparkApplication
        metadata:
          name: spark-app
        spec:
          type: Scala
          mode: cluster
          image: gcr.io/spark-operator/spark:v3.1.1
          imagePullPolicy: Always
          mainClass: org.apache.spark.examples.SparkPi
          mainApplicationFile:  local:///opt/spark/spark-examples_2.12-3.1.1.jar
          sparkVersion: "3.1.1"
          driver:
            cores: 1
            coreLimit: "1200m"
            memory: "512m"
            serviceAccount: spark
            labels:
              version: 3.1.1
          executor:
            cores: 1
            instances: 1
            memory: "512m"
            labels:
              version: 3.1.1