apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gitclient
  name: gitclient
  namespace: gitlab
spec:
  containers:
  - image: alpine/git
    name: gitclient
    command: ["/bin/sh"]
    args: ["-c", "tail -f /dev/null"]