apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: jhub
spec:
  selector:
    app: jupyterhub
    component: singleuser-server
  ports:
    - name: driver-rpc-port
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: blockmanager
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: spark-driver-ui-port
      port: 4040
      protocol: TCP
      targetPort: 4040
  type: ClusterIP
  # ports:
  #   - name: driver-rpc-port
  #     protocol: TCP
  #     port: 2222
  #     targetPort: 2222
  #     nodePort: 32570
  #   - name: blockmanager
  #     protocol: TCP
  #     port: 7777
  #     targetPort: 7777
  #     nodePort: 32571
  #   - name: spark-driver-ui-port
  #     port: 4040
  #     protocol: TCP
  #     targetPort: 4040
  #     nodePort: 32572
  # type: NodePort