global:
  ## https://docs.gitlab.com/charts/installation/deployment#deploy-the-community-edition
  edition: cd   # modify ee to ce (community-edition)

  ## https://docs.gitlab.com/charts/charts/globals#configure-host-settings
  hosts:
    domain: localhost.com   # 다른 설정 안하면 prefix로 gitlab 붙음
    gitlab: 
      name: gitlab.localhost.com  # 호스트 도메인 명
      https: true                 # https 허용
    minio: 
      name: minio.localhost.com   # MinIO 호스트 도메인 명
      https: true                 # https 허용
    registry: 
      name: minio.localhost.com   # Registry 호스트 도메인 명
      https: true                 # https 허용

  ## https://docs.gitlab.com/charts/charts/globals#configure-ingress-settings
  ingress:
    configureCertmanager: false   # 사용하지 않음
    class: nginx                  # 지정하지 않으면 gitlab-nginx 클래스가 생성됨
    tls:
      enabled: true               # 활성화

## Settings to for the Let's Encrypt ACME Issuer
certmanager-issuer:           # certmanager issuer 발급을 위해 활성화
#   # The email address to register certificates requested from Let's Encrypt.
#   # Required if using Let's Encrypt.
  email: ccambo@acornsoft.io

## Installation & configuration of jetstack/cert-manager
## See requirements.yaml for current version
certmanager:
  install: false              # 이미 설치된 cert-manager를 활용할 것이므로 false 처리

## https://docs.gitlab.com/charts/charts/nginx/
## https://docs.gitlab.com/charts/architecture/decisions#nginx-ingress
## Installation & configuration of charts/ingress-nginx:
nginx-ingress:
  enabled: false              # 사용하지 않는 것으로 처리
  controller:
    service:
      externalTrafficPolicy: "Local"