kind: Service
apiVersion: v1
metadata:
  name: terminal
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: terminal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: terminal
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app.kubernetes.io/name: terminal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: terminal
    app.kubernetes.io/part-of: {{ .Chart.Name }}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/name: terminal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: terminal
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: terminal
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: terminal
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      app.kubernetes.io/managed-by: helm
      app.kubernetes.io/component: terminal
      app.kubernetes.io/part-of: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: terminal
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/component: terminal
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      containers:
        - name: terminal
          image: ghcr.io/kore3lab/kore-board.terminal:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.terminal.resources }}
          resources: {{- toYaml .Values.terminal.resources | nindent 12 }}
          {{- end }}
          args:
            - --kubeconfig=/app/.kube/config
            - --log-level=info
          ports:
            - containerPort: 3003
              protocol: TCP
          volumeMounts:
            - mountPath: /app/.kube
              name: kubeconfig
          securityContext:
            privileged: true
      volumes:
        - name: kubeconfig
          configMap:
            name: {{ .Chart.Name }}-kubeconfig
      serviceAccountName: {{ .Chart.Name }}
      nodeSelector:
        "kubernetes.io/os": linux

