stages:
- build

variables:
    DEP_VERSION: "0.5.3"

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk --no-cache add git
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY ;
    - >
      if [ "${SPARK_REGISTRY}" != "" -a "${SPARK_VERSION}" != "" ] ; then
        tagStamp=$(git describe --tags --dirty)_${SPARK_VERSION}
        echo Using SPARK_IMAGE ${SPARK_REGISTRY}:${SPARK_VERSION}
        echo CI_REGISTRY_IMAGE_TAG is ${CI_REGISTRY_IMAGE}/spark-operator:${tagStamp}
        docker build --build-arg SPARK_IMAGE=${SPARK_REGISTRY}:${SPARK_VERSION} -t ${CI_REGISTRY_IMAGE}/spark-operator:${tagStamp} .
      else
        tagStamp=$(git describe --tags --dirty) ; echo tagStamp is ${tagStamp} ;
        echo CI_REGISTRY_IMAGE_TAG is ${CI_REGISTRY_IMAGE}/spark-operator:${tagStamp}
        docker build -t ${CI_REGISTRY_IMAGE}/spark-operator:${tagStamp} .
      fi
    - time docker push ${CI_REGISTRY_IMAGE}/spark-operator:${tagStamp}
    - docker images
