apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-zoekt.configMapName" . }}
  labels:
    {{- include "gitlab-zoekt.labels" . | nindent 4 }}
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;

    events {
        use epoll;
    }

    http {
        server {
            {{- if .Values.gateway.tls.certificate.enabled }}
            listen       {{ .Values.gateway.listen.port }} ssl;
            ssl_certificate /etc/ssl/tls.crt;
            ssl_certificate_key /etc/ssl/tls.key;
            ssl_protocols TLSv1.2 TLSv1.3;
            {{- else }}
            listen       {{ .Values.gateway.listen.port }};
            {{- end }}
            server_tokens off;

            location / {
              proxy_pass http://127.0.0.1:{{ .Values.webserver.listen.port }}/;
            }
        }
    }
