---
# tasks file for tmp

- name: Template add in Master[0]
  template:
    src: "{{ grafana }}.yaml.j2"
    dest: "{{ ansible_env.HOME }}/carrier/{{ grafana }}.yaml"
    mode: 0644

- name: Install grafana from Helm Charts
  when: {{ installed.grafana }}
  kubernetes.core.helm:
    name: "{{ grafana }}"
    kubeconfig: "{{ kubeconfig }}"
    atomic: true    # 설치 실패시 삭제 처리
    chart_ref: "{{ helm_repository_name }}/grafana"
    chart_version: "{{ chart_version['grafana'] }}"
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: true
    values_files:
      - "{{ helm_value_dir }}/{{ grafana }}.yaml"