---
# tasks file for Istio

- name: Template add in Master[0]
  template:
    # src: "{{ istio }}.yaml.j2"
    src: "/Users/dongmook/git-workspaces/edgecarrier/roles/carrier/install/templates/{{ istio }}.yaml.j2"
    dest: "{{ ansible_env.HOME }}/carrier/{{ istio }}.yaml"
    mode: 0644

- name: Install Istio
  when: "{{ installed.istio }}"
  command: "istioctl apply --kubeconfig='{{kubeconfig}}' --skip-confirmation -f {{ ansible_env.HOME }}/carrier/{{ istio }}.yaml"