---
# tasks file for tmp

- name: Template add in Master[0]
  template:
    src: "{{ jaeger }}.yaml.j2"
    dest: "{{ ansible_env.HOME }}/carrier/{{ jaeger }}.yaml"
    mode: 0644

- name: Install jaeger from Helm Charts
  when: jaeger_install
  kubernetes.core.helm:
    name: {{ jaeger }}
    kubeconfig: "{{ kubeconfig }}"
    chart_ref: "{{ helm_repository_name }}/jaeger-operator"
    # chart_version: "2.21.3"
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: true
    values_files:
      - "{{ helm_value_dir }}/{{ jaeger }}.yaml"