---
# tasks file for kubesphere

- name: Template add in Master[0]
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/carrier/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: "{{ kubesphere }}.yaml.j2", dest: "{{ kubesphere }}.yaml" }
    - { src: "{{ kubesphere }}.sh.j2", dest: "{{ kubesphere }}.sh" }
    - { src: "{{ kubesphere }}_provisionercapabilities.yaml.j2", dest: "{{ kubesphere }}_provisionercapabilities.yaml" }

- name: kubesphere k8s install provisionercapabilities crd in cluster
  when: "{{ installed.kubesphere }}"
  kubernetes.core.k8s:
    # name: "{{ kubesphere }}"
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ kubesphere_namespace }}"
    state: present
    src: "{{ ansible_env.HOME }}/carrier/{{ kubesphere }}_provisionercapabilities.yaml"
    wait: true

- name: Install kubesphere from Helm Charts
  when: "{{ installed.kubesphere }}"
  kubernetes.core.helm:
    name: "{{ kubesphere }}"
    kubeconfig: "{{ kubeconfig }}"
    atomic: true    # 설치 실패시 삭제 처리
    chart_ref: "{{ helm_repository_name }}/ks-installer"
    chart_version: "{{ chart_version['ks-installer'] }}"
    release_namespace: "{{ kubesphere_namespace }}"
    create_namespace: true
    values_files:
      - "{{ helm_value_dir }}/{{ kubesphere }}.yaml"