---
#- include_tasks: grafana-task.yml

# # nexus include task
# - include_tasks: nexus-task.yml

# # kore-board include task
# - include_tasks: koreboard-task.yml

# # zabbix include task
# - include_tasks: zabbix-task.yml

# kong/konga include task
# - include_tasks: kong-task.yml

# kong/konga include task
- include_tasks: argocd-task.yml
