---
# kiali include task
#- include: kiali-task.yml

# jaeger include task
#- include: jaeger-task.yml

# prometheus include task
#- include: prometheus-task.yml

# grafana include task
#- include: grafana-task.yml

# # nexus include task
# - include: nexus-task.yml

# # kore-board include task
# - include: koreboard-task.yml

# # zabbix include task
# - include: zabbix-task.yml

# kong/konga include task
# - include: kong-task.yml

# jupyterhub include task
# - include: jupyterhub-task.yml

# gitlab include task
# - include: gitlab-task.yml

# spark include task
#- include: spark-task.yml

- name: Install Task for ArgoCD
  when: installed.common
  include: init-task.yml
  tags: common

- name: Install Task for ArgoCD
  when: installed.argocd
  include: argocd-task.yml
  tags: argocd

- name: Install Task for Consul
  when: installed.consul
  include: consul-task.yml
  tags: consul

- name: Install Task for GitLab
  when: installed.gitlab
  include: gitlab-task.yml
  tags: gitlab

- name: Install Task for Grafana
  when: installed.grafana
  include: grafana-task.yml
  tags: grafana

- name: Install Task for Istio
  when: installed.istio
  include: istio-task.yml
  tags: istio

- name: Install Task for Jaeger
  when: installed.jaeger
  include: jaeger-task.yml
  tags: jaeger

- name: Install Task for Jupyterhub
  when: installed.jupyterhub
  include: jupyterhub-task.yml
  tags: jupyterhub

- name: Install Task for Kiali
  when: installed.kiali
  include: kiali-task.yml
  tags: kiali

- name: Install Task for Kong/Konga
  when: installed.kong
  include: kong-task.yml
  tags: kong

- name: Install Task for KoreBoard
  when: installed.koreboard
  include: koreboard-task.yml
  tags: koreboard

- name: Install Task for Kubesphere
  when: installed.kubesphere
  include: kubesphere-task.yml
  tags: kubesphere

- name: Install Task for Nexus
  when: installed.nexus
  include: nexus-task.yml
  tags: nexus

- name: Install Task for Prometheus
  when: installed.prometheus
  include: prometheus-task.yml
  tags: prometheus

- name: Install Task for Spark
  when: installed.spark
  include: spark-task.yml
  tags: spark

- name: Install Task for Zabbix
  when: installed.zabbix
  include: zabbix-task.yml
  tags: zabbix