---
# tasks file for tmp

- name: Template add in Master[0]
  template:
    src: "{{ prometheus }}.yaml.j2"
    dest: "{{ ansible_env.HOME }}/carrier/{{ prometheus }}.yaml"
    mode: 0644

- name: Install Prometheus from Helm Charts
  when: {{ installed.prometheus }}
  kubernetes.core.helm:
    name: "{{ prometheus }}"
    kubeconfig: "{{ kubeconfig }}"
    atomic: true    # 설치 실패시 삭제 처리
    chart_ref: "{{ helm_repository_name }}/prometheus"
    chart_version: "{{ chart_version['prometheus'] }}"
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: true
    values_files:
      - "{{ helm_value_dir }}/{{ prometheus }}.yaml"
