---
- name: Spark Template add in Cluster
  template:
    src: "{{ spark }}.yaml.j2"
    dest: "{{ ansible_env.HOME }}/carrier/{{ spark }}.yaml"
    mode: 0644

- name: Install Spark in Cluster
  kubernetes.core.helm:
    name: "{{ spark }}"
    kubeconfig: "{{ kubeconfig }}"
    atomic: true    # 설치 실패시 삭제 처리
    chart_ref: "{{ helm_repository_name }}/spark-operator"
    chart_version: "{{ chart_version['spark'] }}"
    release_namespace: "{{ spark }}-operator"
    create_namespace: true
    values_files:
      - "{{ helm_value_dir }}/{{ spark }}.yaml"

