---
- name: ArgoCD remove in cluster
  kubernetes.core.helm:
    name: "{{ argocd }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ argocd }}"
    state: absent
    wait: true
    values_files:
      - "{{ helm_value_dir }}/{{ argocd }}.yaml"