---
- name: Zabbix remove in cluster
  kubernetes.core.helm:
    name: "{{ zabbix }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ monitoring_namespace }}"
    state: absent
    wait: true
    values_files:
      - "{{ helm_value_dir }}/{{ zabbix }}.yaml"