---
# tasks file for nginx
# - name: Add helm repo
#   kubernetes.core.helm_repository:
#     name: bitnami
#     repo_url: "{{ helm_chart_url }}"

# - name: Add carrier directory
#   command: "mkdir {{ ansible_env.HOME }}/carrier"

- name: add template
  template:
    src: "{{ item.src }}"
    dest: "{{ helm_value_dir }}/{{ item.dest }}"
    mode: 0644
  with_items:
    # - { src: "value.yaml.j2", dest: "test-values.yaml" }
    - { src: "{{prometheus_value_name}}.j2", dest: "{{prometheus_value_name}}" }

- name: Install Prometheus from Helm Charts
  kubernetes.core.helm:
    name: prometheus
    kubeconfig: "{{kubeconfig}}"
    chart_ref: "{{helm_repository_name}}/prometheus"
    release_namespace: "{{release_namespace}}"
    create_namespace: true
    values_files:
      - "{{ helm_value_dir }}/{{prometheus_value_name}}"

# - name: Gather information about prometheus
#   kubernetes.core.helm_info:
#     name: prometheus
#     release_namespace: "{{release_namespace}}"