apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-cluster
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
rules:
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: jhub
roleRef:
  kind: Role
  name: spark-cluster
  apiGroup: rbac.authorization.k8s.io