apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjazoKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwOi8vMTkyLjE2OC44OC4xMTo1MDAwL3YzLwogICAgICB1c2VybmFtZTogImVkZ2VjcmFmdCIKICAgICAgcGFzc3dvcmQ6ICJQYXNzMDAwMEAiCiAgICAgIHByb2plY3RfaWQ6IDZiZDI0MGZmNjgyNjQ5NTI4YWY5ODZjM2M4YzVlMzZjCiAgICAgIHByb2plY3RfbmFtZTogImVkZ2VjcmFmdC1jbG9zZSIKICAgICAgdXNlcl9kb21haW5fbmFtZTogIkRlZmF1bHQiCiAgICByZWdpb25fbmFtZTogIlJlZ2lvbk9uZSIKICAgIGludGVyZmFjZTogInB1YmxpYyIKICAgIGlkZW50aXR5X2FwaV92ZXJzaW9uOiAz
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: closed-kubeadm-provisioning-1-cloud-config
  namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: closed-kubeadm-provisioning-1-worker-node
  namespace: default
spec:
  template:
    spec:
      files:
      - content: Cg==
        encoding: base64
        owner: root
        path: /etc/certs/cacert
        permissions: "0600"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
      preKubeadmCommands:
      - echo "10.10.10.16 regi.edgecraft.acornsoft.io" >> /etc/hosts
      - mkdir -p /etc/docker/certs.d/10.10.10.16
      - curl -Lk https://10.10.10.16/ca.crt -o /etc/docker/certs.d/10.10.10.16/ca.crt
      - rm -rf /etc/containerd/certs.d
      - mkdir -p /etc/containerd/certs.d/10.10.10.16
      - echo c2VydmVyID0gImh0dHBzOi8vMTAuMTAuMTAuMTYiCgpbaG9zdC4iaHR0cHM6Ly8xMC4xMC4xMC4xNiJdCiAgY2EgPSAiL2V0Yy9kb2NrZXIvY2VydHMuZC8xMC4xMC4xMC4xNi9jYS5jcnQi
        | base64 -d > /etc/containerd/certs.d/10.10.10.16/hosts.toml
      - mkdir -p /etc/containerd/certs.d/docker.io
      - echo c2VydmVyID0gImh0dHBzOi8vZG9ja2VyLmlvIgoKW2hvc3QuImh0dHBzOi8vMTAuMTAuMTAuMTYvdjIvZG9ja2VyLmlvLyJdCiAgY2FwYWJpbGl0aWVzID0gWyJwdWxsIiwgInJlc29sdmUiXQogIGNhID0gIi9ldGMvZG9ja2VyL2NlcnRzLmQvMTAuMTAuMTAuMTYvY2EuY3J0IgogIG92ZXJyaWRlX3BhdGggPSB0cnVl
        | base64 -d > /etc/containerd/certs.d/docker.io/hosts.toml
      - mkdir -p /etc/containerd/certs.d/gcr.io
      - echo c2VydmVyID0gImh0dHBzOi8vZ2NyLmlvIgoKW2hvc3QuImh0dHBzOi8vMTAuMTAuMTAuMTYvdjIvZ2NyLmlvLyJdCiAgY2FwYWJpbGl0aWVzID0gWyJwdWxsIiwgInJlc29sdmUiXQogIGNhID0gIi9ldGMvZG9ja2VyL2NlcnRzLmQvMTAuMTAuMTAuMTYvY2EuY3J0IgogIG92ZXJyaWRlX3BhdGggPSB0cnVl
        | base64 -d > /etc/containerd/certs.d/gcr.io/hosts.toml
      - mkdir -p /etc/containerd/certs.d/ghcr.io
      - echo c2VydmVyID0gImh0dHBzOi8vZ2hjci5pbyIKCltob3N0LiJodHRwczovLzEwLjEwLjEwLjE2L3YyL2doY3IuaW8vIl0KICBjYXBhYmlsaXRpZXMgPSBbInB1bGwiLCAicmVzb2x2ZSJdCiAgY2EgPSAiL2V0Yy9kb2NrZXIvY2VydHMuZC8xMC4xMC4xMC4xNi9jYS5jcnQiCiAgb3ZlcnJpZGVfcGF0aCA9IHRydWU=
        | base64 -d > /etc/containerd/certs.d/ghcr.io/hosts.toml
      - mkdir -p /etc/containerd/certs.d/quay.io
      - echo c2VydmVyID0gImh0dHBzOi8vcXVheS5pbyIKCltob3N0LiJodHRwczovLzEwLjEwLjEwLjE2L3YyL3F1YXkuaW8vIl0KICBjYXBhYmlsaXRpZXMgPSBbInB1bGwiLCAicmVzb2x2ZSJdCiAgY2EgPSAiL2V0Yy9kb2NrZXIvY2VydHMuZC8xMC4xMC4xMC4xNi9jYS5jcnQiCiAgb3ZlcnJpZGVfcGF0aCA9IHRydWU=
        | base64 -d > /etc/containerd/certs.d/quay.io/hosts.toml
      - mkdir -p /etc/containerd/certs.d/registry.k8s.io
      - echo c2VydmVyID0gImh0dHBzOi8vcmVnaXN0cnkuazhzLmlvIgoKW2hvc3QuImh0dHBzOi8vMTAuMTAuMTAuMTYvdjIvcmVnaXN0cnkuazhzLmlvLyJdCiAgY2FwYWJpbGl0aWVzID0gWyJwdWxsIiwgInJlc29sdmUiXQogIGNhID0gIi9ldGMvZG9ja2VyL2NlcnRzLmQvMTAuMTAuMTAuMTYvY2EuY3J0IgogIG92ZXJyaWRlX3BhdGggPSB0cnVl
        | base64 -d > /etc/containerd/certs.d/registry.k8s.io/hosts.toml
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: closed-kubeadm-provisioning-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.96.0.1/12
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: closed-kubeadm-provisioning-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
    kind: OpenStackCluster
    name: closed-kubeadm-provisioning-1
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: closed-kubeadm-provisioning-1-worker-node
  namespace: default
spec:
  clusterName: closed-kubeadm-provisioning-1
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: closed-kubeadm-provisioning-1-worker-node
      clusterName: closed-kubeadm-provisioning-1
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
        kind: OpenStackMachineTemplate
        name: closed-kubeadm-provisioning-1-worker-node
      version: v1.26.1
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: closed-kubeadm-provisioning-1-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    files:
    - content: YXBpVmVyc2lvbjogdjEKaXRlbXM6Ci0gYXBpVmVyc2lvbjogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pby92MQogIGtpbmQ6IENsdXN0ZXJSb2xlCiAgbWV0YWRhdGE6CiAgICBuYW1lOiBzeXN0ZW06Y2xvdWQtY29udHJvbGxlci1tYW5hZ2VyCiAgcnVsZXM6CiAgLSBhcGlHcm91cHM6CiAgICAtIGNvb3JkaW5hdGlvbi5rOHMuaW8KICAgIHJlc291cmNlczoKICAgIC0gbGVhc2VzCiAgICB2ZXJiczoKICAgIC0gZ2V0CiAgICAtIGNyZWF0ZQogICAgLSB1cGRhdGUKICAtIGFwaUdyb3VwczoKICAgIC0gIiIKICAgIHJlc291cmNlczoKICAgIC0gZXZlbnRzCiAgICB2ZXJiczoKICAgIC0gY3JlYXRlCiAgICAtIHBhdGNoCiAgICAtIHVwZGF0ZQogIC0gYXBpR3JvdXBzOgogICAgLSAiIgogICAgcmVzb3VyY2VzOgogICAgLSBub2RlcwogICAgdmVyYnM6CiAgICAtICcqJwogIC0gYXBpR3JvdXBzOgogICAgLSAiIgogICAgcmVzb3VyY2VzOgogICAgLSBub2Rlcy9zdGF0dXMKICAgIHZlcmJzOgogICAgLSBwYXRjaAogIC0gYXBpR3JvdXBzOgogICAgLSAiIgogICAgcmVzb3VyY2VzOgogICAgLSBzZXJ2aWNlcwogICAgdmVyYnM6CiAgICAtIGxpc3QKICAgIC0gcGF0Y2gKICAgIC0gdXBkYXRlCiAgICAtIHdhdGNoCiAgLSBhcGlHcm91cHM6CiAgICAtICIiCiAgICByZXNvdXJjZXM6CiAgICAtIHNlcnZpY2VzL3N0YXR1cwogICAgdmVyYnM6CiAgICAtIHBhdGNoCiAgLSBhcGlHcm91cHM6CiAgICAtICIiCiAgICByZXNvdXJjZXM6CiAgICAtIHNlcnZpY2VhY2NvdW50cwogICAgdmVyYnM6CiAgICAtIGNyZWF0ZQogICAgLSBnZXQKICAtIGFwaUdyb3VwczoKICAgIC0gIiIKICAgIHJlc291cmNlczoKICAgIC0gc2VydmljZWFjY291bnRzL3Rva2VuCiAgICB2ZXJiczoKICAgIC0gY3JlYXRlCiAgLSBhcGlHcm91cHM6CiAgICAtICIiCiAgICByZXNvdXJjZXM6CiAgICAtIHBlcnNpc3RlbnR2b2x1bWVzCiAgICB2ZXJiczoKICAgIC0gJyonCiAgLSBhcGlHcm91cHM6CiAgICAtICIiCiAgICByZXNvdXJjZXM6CiAgICAtIGVuZHBvaW50cwogICAgdmVyYnM6CiAgICAtIGNyZWF0ZQogICAgLSBnZXQKICAgIC0gbGlzdAogICAgLSB3YXRjaAogICAgLSB1cGRhdGUKICAtIGFwaUdyb3VwczoKICAgIC0gIiIKICAgIHJlc291cmNlczoKICAgIC0gY29uZmlnbWFwcwogICAgdmVyYnM6CiAgICAtIGdldAogICAgLSBsaXN0CiAgICAtIHdhdGNoCiAgLSBhcGlHcm91cHM6CiAgICAtICIiCiAgICByZXNvdXJjZXM6CiAgICAtIHNlY3JldHMKICAgIHZlcmJzOgogICAgLSBsaXN0CiAgICAtIGdldAogICAgLSB3YXRjaAotIGFwaVZlcnNpb246IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8vdjEKICBraW5kOiBDbHVzdGVyUm9sZQogIG1ldGFkYXRhOgogICAgbmFtZTogc3lzdGVtOmNsb3VkLW5vZGUtY29udHJvbGxlcgogIHJ1bGVzOgogIC0gYXBpR3JvdXBzOgogICAgLSAiIgogICAgcmVzb3VyY2VzOgogICAgLSBub2RlcwogICAgdmVyYnM6CiAgICAtICcqJwogIC0gYXBpR3JvdXBzOgogICAgLSAiIgogICAgcmVzb3VyY2VzOgogICAgLSBub2Rlcy9zdGF0dXMKICAgIHZlcmJzOgogICAgLSBwYXRjaAogIC0gYXBpR3JvdXBzOgogICAgLSAiIgogICAgcmVzb3VyY2VzOgogICAgLSBldmVudHMKICAgIHZlcmJzOgogICAgLSBjcmVhdGUKICAgIC0gcGF0Y2gKICAgIC0gdXBkYXRlCmtpbmQ6IExpc3QKbWV0YWRhdGE6IHt9Cg==
      encoding: base64
      owner: root
      path: /etc/kubernetes/addon/openstack/cloud-controller-manager-roles.yaml
      permissions: "0600"
    - content: YXBpVmVyc2lvbjogdjEKaXRlbXM6Ci0gYXBpVmVyc2lvbjogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pby92MQogIGtpbmQ6IENsdXN0ZXJSb2xlQmluZGluZwogIG1ldGFkYXRhOgogICAgbmFtZTogc3lzdGVtOmNsb3VkLW5vZGUtY29udHJvbGxlcgogIHJvbGVSZWY6CiAgICBhcGlHcm91cDogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pbwogICAga2luZDogQ2x1c3RlclJvbGUKICAgIG5hbWU6IHN5c3RlbTpjbG91ZC1ub2RlLWNvbnRyb2xsZXIKICBzdWJqZWN0czoKICAtIGtpbmQ6IFNlcnZpY2VBY2NvdW50CiAgICBuYW1lOiBjbG91ZC1ub2RlLWNvbnRyb2xsZXIKICAgIG5hbWVzcGFjZToga3ViZS1zeXN0ZW0KLSBhcGlWZXJzaW9uOiByYmFjLmF1dGhvcml6YXRpb24uazhzLmlvL3YxCiAga2luZDogQ2x1c3RlclJvbGVCaW5kaW5nCiAgbWV0YWRhdGE6CiAgICBuYW1lOiBzeXN0ZW06Y2xvdWQtY29udHJvbGxlci1tYW5hZ2VyCiAgcm9sZVJlZjoKICAgIGFwaUdyb3VwOiByYmFjLmF1dGhvcml6YXRpb24uazhzLmlvCiAgICBraW5kOiBDbHVzdGVyUm9sZQogICAgbmFtZTogc3lzdGVtOmNsb3VkLWNvbnRyb2xsZXItbWFuYWdlcgogIHN1YmplY3RzOgogIC0ga2luZDogU2VydmljZUFjY291bnQKICAgIG5hbWU6IGNsb3VkLWNvbnRyb2xsZXItbWFuYWdlcgogICAgbmFtZXNwYWNlOiBrdWJlLXN5c3RlbQpraW5kOiBMaXN0Cm1ldGFkYXRhOiB7fQ==
      encoding: base64
      owner: root
      path: /etc/kubernetes/addon/openstack/cloud-controller-manager-role-bindings.yaml
      permissions: "0600"
    - content: LS0tCmFwaVZlcnNpb246IHYxCmtpbmQ6IFNlcnZpY2VBY2NvdW50Cm1ldGFkYXRhOgogIG5hbWU6IGNsb3VkLWNvbnRyb2xsZXItbWFuYWdlcgogIG5hbWVzcGFjZToga3ViZS1zeXN0ZW0KLS0tCmFwaVZlcnNpb246IGFwcHMvdjEKa2luZDogRGFlbW9uU2V0Cm1ldGFkYXRhOgogIG5hbWU6IG9wZW5zdGFjay1jbG91ZC1jb250cm9sbGVyLW1hbmFnZXIKICBuYW1lc3BhY2U6IGt1YmUtc3lzdGVtCiAgbGFiZWxzOgogICAgazhzLWFwcDogb3BlbnN0YWNrLWNsb3VkLWNvbnRyb2xsZXItbWFuYWdlcgpzcGVjOgogIHNlbGVjdG9yOgogICAgbWF0Y2hMYWJlbHM6CiAgICAgIGs4cy1hcHA6IG9wZW5zdGFjay1jbG91ZC1jb250cm9sbGVyLW1hbmFnZXIKICB1cGRhdGVTdHJhdGVneToKICAgIHR5cGU6IFJvbGxpbmdVcGRhdGUKICB0ZW1wbGF0ZToKICAgIG1ldGFkYXRhOgogICAgICBsYWJlbHM6CiAgICAgICAgazhzLWFwcDogb3BlbnN0YWNrLWNsb3VkLWNvbnRyb2xsZXItbWFuYWdlcgogICAgc3BlYzoKICAgICAgbm9kZVNlbGVjdG9yOgogICAgICAgIG5vZGUtcm9sZS5rdWJlcm5ldGVzLmlvL2NvbnRyb2wtcGxhbmU6ICIiCiAgICAgIHNlY3VyaXR5Q29udGV4dDoKICAgICAgICBydW5Bc1VzZXI6IDEwMDEKICAgICAgdG9sZXJhdGlvbnM6CiAgICAgIC0ga2V5OiBub2RlLmNsb3VkcHJvdmlkZXIua3ViZXJuZXRlcy5pby91bmluaXRpYWxpemVkCiAgICAgICAgdmFsdWU6ICJ0cnVlIgogICAgICAgIGVmZmVjdDogTm9TY2hlZHVsZQogICAgICAtIGtleTogbm9kZS1yb2xlLmt1YmVybmV0ZXMuaW8vbWFzdGVyCiAgICAgICAgZWZmZWN0OiBOb1NjaGVkdWxlCiAgICAgIC0ga2V5OiBub2RlLXJvbGUua3ViZXJuZXRlcy5pby9jb250cm9sLXBsYW5lCiAgICAgICAgZWZmZWN0OiBOb1NjaGVkdWxlCiAgICAgIHNlcnZpY2VBY2NvdW50TmFtZTogY2xvdWQtY29udHJvbGxlci1tYW5hZ2VyCiAgICAgIGNvbnRhaW5lcnM6CiAgICAgICAgLSBuYW1lOiBvcGVuc3RhY2stY2xvdWQtY29udHJvbGxlci1tYW5hZ2VyCiAgICAgICAgICBpbWFnZTogcmVnaXN0cnkuazhzLmlvL3Byb3ZpZGVyLW9zL29wZW5zdGFjay1jbG91ZC1jb250cm9sbGVyLW1hbmFnZXI6djEuMjcuMQogICAgICAgICAgYXJnczoKICAgICAgICAgICAgLSAvYmluL29wZW5zdGFjay1jbG91ZC1jb250cm9sbGVyLW1hbmFnZXIKICAgICAgICAgICAgLSAtLXY9MQogICAgICAgICAgICAtIC0tY2x1c3Rlci1uYW1lPSQoQ0xVU1RFUl9OQU1FKQogICAgICAgICAgICAtIC0tY2xvdWQtY29uZmlnPSQoQ0xPVURfQ09ORklHKQogICAgICAgICAgICAtIC0tY2xvdWQtcHJvdmlkZXI9b3BlbnN0YWNrCiAgICAgICAgICAgIC0gLS11c2Utc2VydmljZS1hY2NvdW50LWNyZWRlbnRpYWxzPXRydWUKICAgICAgICAgICAgLSAtLWJpbmQtYWRkcmVzcz0xMjcuMC4wLjEKICAgICAgICAgIHZvbHVtZU1vdW50czoKICAgICAgICAgICAgLSBtb3VudFBhdGg6IC9ldGMva3ViZXJuZXRlcy9wa2kKICAgICAgICAgICAgICBuYW1lOiBrOHMtY2VydHMKICAgICAgICAgICAgICByZWFkT25seTogdHJ1ZQogICAgICAgICAgICAtIG1vdW50UGF0aDogL2V0Yy9zc2wvY2VydHMKICAgICAgICAgICAgICBuYW1lOiBjYS1jZXJ0cwogICAgICAgICAgICAgIHJlYWRPbmx5OiB0cnVlCiAgICAgICAgICAgIC0gbW91bnRQYXRoOiAvZXRjL2NvbmZpZwogICAgICAgICAgICAgIG5hbWU6IGNsb3VkLWNvbmZpZy12b2x1bWUKICAgICAgICAgICAgICByZWFkT25seTogdHJ1ZQogICAgICAgICAgcmVzb3VyY2VzOgogICAgICAgICAgICByZXF1ZXN0czoKICAgICAgICAgICAgICBjcHU6IDIwMG0KICAgICAgICAgIGVudjoKICAgICAgICAgICAgLSBuYW1lOiBDTE9VRF9DT05GSUcKICAgICAgICAgICAgICB2YWx1ZTogL2V0Yy9jb25maWcvY2xvdWQuY29uZgogICAgICAgICAgICAtIG5hbWU6IENMVVNURVJfTkFNRQogICAgICAgICAgICAgIHZhbHVlOiBrdWJlcm5ldGVzCiAgICAgIGhvc3ROZXR3b3JrOiB0cnVlCiAgICAgIHZvbHVtZXM6CiAgICAgIC0gaG9zdFBhdGg6CiAgICAgICAgICBwYXRoOiAvZXRjL2t1YmVybmV0ZXMvcGtpCiAgICAgICAgICB0eXBlOiBEaXJlY3RvcnlPckNyZWF0ZQogICAgICAgIG5hbWU6IGs4cy1jZXJ0cwogICAgICAtIGhvc3RQYXRoOgogICAgICAgICAgcGF0aDogL2V0Yy9zc2wvY2VydHMKICAgICAgICAgIHR5cGU6IERpcmVjdG9yeU9yQ3JlYXRlCiAgICAgICAgbmFtZTogY2EtY2VydHMKICAgICAgLSBuYW1lOiBjbG91ZC1jb25maWctdm9sdW1lCiAgICAgICAgc2VjcmV0OgogICAgICAgICAgc2VjcmV0TmFtZTogY2xvdWQtY29uZmln
      encoding: base64
      owner: root
      path: /etc/kubernetes/addon/openstack/openstack-cloud-controller-manager-ds.yaml
      permissions: "0600"
    - content: W0dsb2JhbF0KYXV0aC11cmw9aHR0cDovLzE5Mi4xNjguODguMTE6NTAwMC92My8KdXNlcm5hbWU9ImVkZ2VjcmFmdCIKcGFzc3dvcmQ9IlBhc3MwMDAwQCIKdGVuYW50LWlkPSI2YmQyNDBmZjY4MjY0OTUyOGFmOTg2YzNjOGM1ZTM2YyIKdGVuYW50LW5hbWU9ImVkZ2VjcmFmdC1jbG9zZSIKZG9tYWluLW5hbWU9IkRlZmF1bHQiCnJlZ2lvbj0iUmVnaW9uT25lIg==
      encoding: base64
      owner: root
      path: /etc/kubernetes/cloud.conf
      permissions: "0600"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    postKubeadmCommands:
    - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addon/calico/calico.yaml
    - kubectl --kubeconfig=/etc/kubernetes/admin.conf create secret -n kube-system
      generic cloud-config --from-file=/etc/kubernetes/cloud.conf
    - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addon/openstack/cloud-controller-manager-roles.yaml
    - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addon/openstack/cloud-controller-manager-role-bindings.yaml
    - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addon/openstack/openstack-cloud-controller-manager-ds.yaml
    preKubeadmCommands:
    - echo "10.10.10.16 regi.edgecraft.acornsoft.io" >> /etc/hosts
    - mkdir -p /etc/docker/certs.d/10.10.10.16
    - curl -Lk https://10.10.10.16/ca.crt -o /etc/docker/certs.d/10.10.10.16/ca.crt
    - rm -rf /etc/containerd/certs.d
    - mkdir -p /etc/containerd/certs.d/10.10.10.16
    - echo c2VydmVyID0gImh0dHBzOi8vMTAuMTAuMTAuMTYiCgpbaG9zdC4iaHR0cHM6Ly8xMC4xMC4xMC4xNiJdCiAgY2EgPSAiL2V0Yy9kb2NrZXIvY2VydHMuZC8xMC4xMC4xMC4xNi9jYS5jcnQi
      | base64 -d > /etc/containerd/certs.d/10.10.10.16/hosts.toml
    - mkdir -p /etc/containerd/certs.d/docker.io
    - echo c2VydmVyID0gImh0dHBzOi8vZG9ja2VyLmlvIgoKW2hvc3QuImh0dHBzOi8vMTAuMTAuMTAuMTYvdjIvZG9ja2VyLmlvLyJdCiAgY2FwYWJpbGl0aWVzID0gWyJwdWxsIiwgInJlc29sdmUiXQogIGNhID0gIi9ldGMvZG9ja2VyL2NlcnRzLmQvMTAuMTAuMTAuMTYvY2EuY3J0IgogIG92ZXJyaWRlX3BhdGggPSB0cnVl
      | base64 -d > /etc/containerd/certs.d/docker.io/hosts.toml
    - mkdir -p /etc/containerd/certs.d/gcr.io
    - echo c2VydmVyID0gImh0dHBzOi8vZ2NyLmlvIgoKW2hvc3QuImh0dHBzOi8vMTAuMTAuMTAuMTYvdjIvZ2NyLmlvLyJdCiAgY2FwYWJpbGl0aWVzID0gWyJwdWxsIiwgInJlc29sdmUiXQogIGNhID0gIi9ldGMvZG9ja2VyL2NlcnRzLmQvMTAuMTAuMTAuMTYvY2EuY3J0IgogIG92ZXJyaWRlX3BhdGggPSB0cnVl
      | base64 -d > /etc/containerd/certs.d/gcr.io/hosts.toml
    - mkdir -p /etc/containerd/certs.d/ghcr.io
    - echo c2VydmVyID0gImh0dHBzOi8vZ2hjci5pbyIKCltob3N0LiJodHRwczovLzEwLjEwLjEwLjE2L3YyL2doY3IuaW8vIl0KICBjYXBhYmlsaXRpZXMgPSBbInB1bGwiLCAicmVzb2x2ZSJdCiAgY2EgPSAiL2V0Yy9kb2NrZXIvY2VydHMuZC8xMC4xMC4xMC4xNi9jYS5jcnQiCiAgb3ZlcnJpZGVfcGF0aCA9IHRydWU=
      | base64 -d > /etc/containerd/certs.d/ghcr.io/hosts.toml
    - mkdir -p /etc/containerd/certs.d/quay.io
    - echo c2VydmVyID0gImh0dHBzOi8vcXVheS5pbyIKCltob3N0LiJodHRwczovLzEwLjEwLjEwLjE2L3YyL3F1YXkuaW8vIl0KICBjYXBhYmlsaXRpZXMgPSBbInB1bGwiLCAicmVzb2x2ZSJdCiAgY2EgPSAiL2V0Yy9kb2NrZXIvY2VydHMuZC8xMC4xMC4xMC4xNi9jYS5jcnQiCiAgb3ZlcnJpZGVfcGF0aCA9IHRydWU=
      | base64 -d > /etc/containerd/certs.d/quay.io/hosts.toml
    - mkdir -p /etc/containerd/certs.d/registry.k8s.io
    - echo c2VydmVyID0gImh0dHBzOi8vcmVnaXN0cnkuazhzLmlvIgoKW2hvc3QuImh0dHBzOi8vMTAuMTAuMTAuMTYvdjIvcmVnaXN0cnkuazhzLmlvLyJdCiAgY2FwYWJpbGl0aWVzID0gWyJwdWxsIiwgInJlc29sdmUiXQogIGNhID0gIi9ldGMvZG9ja2VyL2NlcnRzLmQvMTAuMTAuMTAuMTYvY2EuY3J0IgogIG92ZXJyaWRlX3BhdGggPSB0cnVl
      | base64 -d > /etc/containerd/certs.d/registry.k8s.io/hosts.toml
    - mkdir -p /etc/kubernetes/addon/calico
    - curl -Lk https://regi.edgecraft.acornsoft.io/download/calico/v3.25.1/calico.yaml
      > /etc/kubernetes/addon/calico/calico.yaml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
      kind: OpenStackMachineTemplate
      name: closed-kubeadm-provisioning-1-control-plane
  replicas: 3
  version: v1.26.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: closed-kubeadm-provisioning-1
  namespace: default
spec:
  apiServerLoadBalancer:
    enabled: false
  cloudName: openstack
  dnsNameservers:
  - 168.126.63.1
  externalNetworkId: 0b189d25-8b67-4c3b-96bb-dcff2ee7f931
  identityRef:
    kind: Secret
    name: closed-kubeadm-provisioning-1-cloud-config
  managedSecurityGroups: false
  nodeCidr: 10.6.0.0/24
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: closed-kubeadm-provisioning-1-control-plane
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: m1.medium
      identityRef:
        kind: Secret
        name: closed-kubeadm-provisioning-1-cloud-config
      image: edgecraft-kube-v1.26.1
      securityGroups:
      - name: edgecraft-closed
      - name: k8s-cluster-secgroup-controlplane
      sshKeyName: hostacloud
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: closed-kubeadm-provisioning-1-worker-node
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: m1.medium
      identityRef:
        kind: Secret
        name: closed-kubeadm-provisioning-1-cloud-config
      image: edgecraft-kube-v1.26.1
      securityGroups:
      - name: edgecraft-closed
      - name: k8s-cluster-secgroup-worker
      sshKeyName: hostacloud
