hub: # Hub Control Panel 설정 
  # service:
  #   type: NodePort   # NodePort로 사용
  #   ports: 
  #     nodePort: 32560
  networkPolicy: 
    interNamespaceAccessLabels: accept 
  extraConfig: 
    httpTimeout: | 
      c.KubeSpawner.http_timeout = 3000

proxy:
  service:
    type: NodePort
    nodePorts:
      http: 32560
      https: 32561

ingress: # 외부와 연결을 위한 Ingress 설정 
  enabled: false
 
singleuser: # 개인마다 JupyterLab이 생성될 때의 설정 
  startTimeout: 600 
  defaultUrl: "/lab" 
  cloudMetadata:
    blockWithIptables: false

cull: 
  enabled: false 

debug:
  enabled: true