apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjazoKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwOi8vMTkyLjE2OC44OC4xMTo1MDAwL3YzLwogICAgICB1c2VybmFtZTogImVkZ2VjcmFmdCIKICAgICAgcGFzc3dvcmQ6ICJQYXNzMDAwMEAiCiAgICAgIHByb2plY3RfaWQ6IGYwMDYwOTllODViMTRjYTJhZWYxZDZjYmMwOTNhNmIxCiAgICAgIHByb2plY3RfbmFtZTogImVkZ2VjcmFmdC1hZG0iCiAgICAgIHVzZXJfZG9tYWluX25hbWU6ICJEZWZhdWx0IgogICAgcmVnaW9uX25hbWU6ICJSZWdpb25PbmUiCiAgICBpbnRlcmZhY2U6ICJwdWJsaWMiCiAgICBpZGVudGl0eV9hcGlfdmVyc2lvbjogMwo=
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: ceph-mk8s-os-cluster-1-cloud-config
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ceph-mk8s-os-cluster-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.96.0.1/12
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: MicroK8sControlPlane
    name: ceph-mk8s-os-cluster-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
    kind: OpenStackCluster
    name: ceph-mk8s-os-cluster-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackCluster
metadata:
  name: ceph-mk8s-os-cluster-1
  namespace: default
spec:
  allowAllInClusterTraffic: true
  apiServerLoadBalancer:
    enabled: false
  cloudName: openstack
  dnsNameservers:
  - 168.126.63.1
  externalNetworkId: public
  identityRef:
    kind: Secret
    name: ceph-mk8s-os-cluster-1-cloud-config
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: MicroK8sControlPlane
metadata:
  name: ceph-mk8s-os-cluster-1-control-plane
  namespace: default
spec:
  controlPlaneConfig:
    initConfiguration:
      addons:
      - dns
      - ingress
  machineTemplate:
    infrastructureTemplate:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
      kind: OpenStackMachineTemplate
      name: ceph-mk8s-os-cluster-1-control-plane
  replicas: 1
  version: v1.23.16
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: ceph-mk8s-os-cluster-1-control-plane
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: 2Core.4G_20GB
      identityRef:
        kind: Secret
        name: ceph-mk8s-os-cluster-1-cloud-config
      image: ubuntu-20.04-capi
      sshKeyName: hostacloud
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ceph-mk8s-os-cluster-1-md-0
  namespace: default
spec:
  clusterName: ceph-mk8s-os-cluster-1
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: MicroK8sConfigTemplate
          name: ceph-mk8s-os-cluster-1-md-0
      clusterName: ceph-mk8s-os-cluster-1
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
        kind: OpenStackMachineTemplate
        name: ceph-mk8s-os-cluster-1-md-0
      version: v1.23.16
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: ceph-mk8s-os-cluster-1-md-0
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: 2Core.4G_20GB
      identityRef:
        kind: Secret
        name: ceph-mk8s-os-cluster-1-cloud-config
      image: ubuntu-20.04-capi
      sshKeyName: hostacloud
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: MicroK8sConfigTemplate
metadata:
  name: ceph-mk8s-os-cluster-1-md-0
  namespace: default
spec:
  template:
    spec: {}
