{{- $fullName := include "pyspark.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName | quote }}
  labels:
    {{- include "pyspark.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - get
    - delete
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - create
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
    - get
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - create
    - list
    - watch
    - delete
